### ISSUE TITLE
KeyError: 'offset'

### ISSUE THREAD

**Issue by thoughtchad** [singer-io/tap-hubspot#20]
Just received an error notification from stitch UI for our beta hubspot integration.
This is all it says: "KeyError: 'offset'"

![image](https://user-images.githubusercontent.com/1541821/26842758-c0a94af2-4aa2-11e7-982a-8baba69acdf6.png)

@iterati Not sure how often the master codeline makes it into the actual stitch jobs... Perhaps something to do with this commit? https://github.com/singer-io/tap-hubspot/commit/512d4969392dffb0b9e20145c58f88215fbc74c0

Do I need to blow everything out and reload perhaps?

**Comment by iterati** [comment]
Fixed in #21

**Comment by iterati** [comment]
You won't need to do anything, the next run will pick up the latest. It appears HubSpot doesn't always return an offset when it's the last page. At least not for the companies endpoint.
