### ISSUE TITLE
ALL deals and companies are sync'd on every run

### ISSUE THREAD

**Issue by jennakertz** [singer-io/tap-hubspot#34]
Hubspot's modified deals and companies endpoints cannot return more than 10,000 results. As such, the Tap requires full syncs of those endpoints in order to get a complete set of historical data with more than 10K results.

Is there a more efficient way to sync deals and companies?

**Comment by iterati** [comment]
Short answer: no.

Longer answer: not until HubSpot makes a better api.

**Comment by thoughtchad** [comment]
Hubspot has a get all contacts. https://developers.hubspot.com/docs/methods/contacts/get_contacts
This works for full load - aka first load. "IF no bookmark, the use CONTACTS_ALL"

Then for future loads, Hubspot has Get recently updated and created contacts. This goes back 30 days... the longest replication setting available in Stitch is 24 hours....
https://developers.hubspot.com/docs/methods/contacts/get_recently_updated_contacts

How is this not possible with the current api?

**Comment by cmerrick** [comment]
This issue is potentially confusing, so a little clarification: although the tap uses the "all" endpoints for deals, companies and contacts, it does internal filtering to only emit records newer than the latest bookmark value.  See, for example, https://github.com/singer-io/tap-hubspot/blob/master/tap_hubspot/__init__.py#L326-L327

So, it's pulling all records every time, only emitting modified records.

**Comment by thoughtchad** [comment]
Hey @cmerrick - Looking at the code that's what I thought.
But it appears that's not what it's doing.
I'm currently only syncing companies and contacts, every 30 minutes. Stitch dashboard currently shows 313,244 rows synced just for today (9/7/2017), yesterday(9/6) it synced 725K rows.

Looking at the actual synced contacts data on my end... the number of rows batched on 9/7 (today) is 536.

So, the real question here is what am I getting charged for?
The # of rows retrieved via contacts_all or the # of rows actually inserted/updated into my destination.

It appears the # of rows retrieved....

**Comment by thoughtchad** [comment]
Looking at the #'s again, It looks like the contacts incremental is working correctly. It's starting to look like the nested tables within contacts (list membership etc) could be the big row count culprits.
