### ISSUE TITLE
Any plans or cons regarding historical values of properties support?

### ISSUE THREAD

**Issue by alexey-pelykh** [singer-io/tap-hubspot#51]

**Comment by briansloane** [comment]
Hi @alexey-pelykh. No immediate plans to add this to the tap but I imagine it would be valuable to some other users of the tap. 

The biggest drawback would be the amount of extra that would be extracted. Adding historical values and putting it behind a configuration would probably be a good way to give people control over the data.

Is this something you're thinking about adding to the tap?

**Comment by briansloane** [comment]
Closing this out for now. Let's re-open if further discussion is needed.
