### ISSUE TITLE
post stitch import webhook

### ISSUE THREAD

**Issue by thoughtchad** [singer-io/tap-hubspot#57]
There is currently not a good way to know when a stitch integration starts or ends. This makes it difficult to schedule additional data processing on the destination. 

It would be ideal for stitch to support webhooks that fired when various stages of the integrations occurred.
Example webhooks:
Extraction Start/End
Loading Start/End

With these webhooks, admins of the destination databases are able to do the following:
 * ensure that destination etl's processes are not running during stitch data loads
 * execute post stitch data load sql, code, processes, etc.

An alternative to this approach - or in addition to - would be the ability to have custom sql scripts execute post stitch data loads. The scripts would be maintained on the stitch front-end.

**Comment by cmerrick** [comment]
Thanks @thoughtchad for the suggestion.  I'm going to close this issue since the suggestion is about Stitch and not the Hubspot tap, but I have recorded it in Stitch's feature request tracking system.
