### ISSUE TITLE
'Click' is not integrated in the schema of campaigns 

### ISSUE THREAD

**Issue by MarioHoH** [singer-io/tap-hubspot#65]
Click is not included and lots of other like drop and bounce, which are all returned by the API. I wish I can have those number in my data warehouse!

**Comment by briansloane** [comment]
@MarioHoH Are these counters on the campaign similar to `delivered`, `open`, etc...? If so, can you create a PR to the campaign schema file? That will allow them to replicate.

https://github.com/singer-io/tap-hubspot/blob/master/tap_hubspot/schemas/campaigns.json
