### ISSUE TITLE
Vanilla hubspot sales does not work out of the box with this tap.

### ISSUE THREAD

**Issue by wss-chadical** [singer-io/tap-hubspot#76]
The company object in Hubspot has a default property called "hs_analytics_last_touch_converting_campaign".

Out of the box this prevents stitch from loading company data into a postgres instance.

Column name too long properties__hs_analytics_last_touch_converting_campaign__timest (63),Column name too long properties__hs_analytics_last_touch_converting_campaign__source (63),Column name too long properties__hs_analytics_first_touch_converting_campaign__sourc (63),field collision on properties__hs_analytics_first_touch_converting_campaign__source

**Comment by timvisher** [comment]
It's unfortunate that this tap can't sync to a PostgreSQL data warehouse with Stitch at the moment but that isn't a direct concern of the tap. Instead, the tap should default to sending as much data as it can and Stitch should handle truncation if it's desirable for their customers.

I'd recommend reaching out to their support for advice on how to overcome this issue.

**Comment by wss-chadical** [comment]
Support says "nope", Customer Success Manager says "nope", Tap dev says "nope", Stitch's private Postgres target says "nope"

The Hubspot Tap docs say it has a minor incompatiblity'.

Hubspot is adding system level properties up the ying-yang - and the names are getting quite long. It won't be long before they add a property to contacts that breaks that as well. Then deals.

FYI Statsbot has a public postgres target that handles this gracefully by reducing wordy stuff with abbreviations. Eg: properties__hs_analytics_last_touch_converting_campaign__timestampz becomes p__hs_analytics_last_touch_converting_campaign__timestampz
https://github.com/statsbotco/target-postgres

Seems like there are ways this could be resolved in many different places - but one one is willing to figure it out.

**Comment by wss-chadical** [comment]
This tap no longer works with Hubspot contacts as well due to long column names.

**Comment by timvisher** [comment]
It's definitely unfortunate. Many deeply nested sources like Mongo suffer from this problem as well. I'm sure if it becomes enough of an issue for enough of their customers Stitch will fix it in their Postgres endpoint as well. I like the approach Statsbot's taking. Are the abbreviations deterministic or can they be different based on how much they have to truncate the names?

Is there anything stopping you from running `tap-hubspot -> statsbot/target-postgres`? If there approach is amenable to your use case then that could get you around this.

**Comment by wss-chadical** [comment]
In the limited testing I've done, the statsbot target only abbreviated when necessary.

It would be great if Stitch were to implement something like this on their closed source postgres target. 

Perhaps a user configurable switch on the stitch destination.

I get it, the targets are supposed to be super generic.
The taps are supposed to send everything, but the targets can't receive 'everything'.
Seems like the singer spec needs some clarification around which side is supposed to deal with these things. I'm not a big fan of both sides saying 'it just won't work'.

In the meantime, I'm going to:
A. Cancel stitch and roll with this Tap plus Statsbot target.
or
B. Use Google BigQuery as the destination. Then use Postgres Foreign Data Wrapper for Big Query to Truncate/Load the data into local Postgres tables.

**Comment by timvisher** [comment]
👍 

If you end up adding some 'more juice' please feel free to open a PR. I'm sure we'd love to have the added functionality. :)
