### ISSUE TITLE
Ensure deals associations are being extracted

### ISSUE THREAD

**Issue by stephlocke** [singer-io/tap-hubspot#77]
Further to a convo with Stitch, the Associations array on the Deals API is being lost. They requested I raise it as an Issue here.

This is the *only* connection to companies and contacts making is very important to have for downstream reporting. 

## Things to do 

- [ ] Validate associations are correctly being retrieved in this tap
- [ ] Add unit tests to verify automatically
- [ ] Fix code if required

**Comment by KAllan357** [comment]
Thanks for the issue @stephlocke. Would you be open to making a PR for this fix? 

I think this could be achieved by adding the `includeAssociations` param to the [parameter map here](https://github.com/singer-io/tap-hubspot/blob/master/tap_hubspot/__init__.py#L441). It should inspect the `mdata` map to determine whether the field is selected and if so the value for `includeAssociations` should be `True`

**Comment by stephlocke** [comment]
I can take a look but it's pretty unlikely I can contribute - python isn't my key language and I'm coming to these repos from stitch versus implementing singer

**Comment by BogdanCojocar** [comment]
Hi, I am trying to submit a PR for this issue, but I get 403. Can I be authorised to write please?

**Comment by stephlocke** [comment]
@BogdanCojocar it might have been an intermittent issue - I just did a sample PR and it worked alright https://github.com/singer-io/tap-hubspot/pull/78

**Comment by timvisher** [comment]
@BogdanCojocar Thanks for working on the issue. It must be a temporary blip. There's nothing on our end that should prevent that that I know of.

**Comment by timvisher** [comment]
@BogdanCojocar Ah sorry I see that you did submit the PR. Thanks! We'll review it asap. :)

**Comment by BogdanCojocar** [comment]
@timvisher Yeah, sorry, it was an issue on my side. Thanks!

**Comment by dmosorast** [comment]
#79 has been merged, and I will be releasing version `2.2.4` with this change. @stephlocke Please close this issue if it fixes what you are seeing, or update it if there are further changes to be made. Thanks!
